#ifndef SDP_W01_LOOPS_H_
#define SDP_W01_LOOPS_H_

#include <cstdint>

// The six loops from Task 1. Each returns how many times its innermost
// statement executed. Read them, derive a formula, and put the formula
// in starter/loop_formulas.cpp. Do not edit this file.
namespace loops {

inline std::uint64_t stepped(std::uint64_t n) {
    std::uint64_t count = 0;
    for (std::uint64_t i = 0; i < n; i += 3) {
        for (int j = 0; j < 5; ++j) {
            ++count;
        }
    }
    return count;
}

inline std::uint64_t square(std::uint64_t n) {
    std::uint64_t count = 0;
    for (std::uint64_t i = 0; i < n; ++i) {
        for (std::uint64_t j = 0; j < n; ++j) {
            ++count;
        }
    }
    return count;
}

inline std::uint64_t triangle(std::uint64_t n) {
    std::uint64_t count = 0;
    for (std::uint64_t i = 0; i < n; ++i) {
        for (std::uint64_t j = 0; j < i; ++j) {
            ++count;
        }
    }
    return count;
}

inline std::uint64_t doubling(std::uint64_t n) {
    std::uint64_t count = 0;
    for (std::uint64_t i = 1; i < n; i *= 2) {
        ++count;
    }
    return count;
}

inline std::uint64_t triple(std::uint64_t n) {
    std::uint64_t count = 0;
    for (std::uint64_t i = 0; i < n; ++i) {
        for (std::uint64_t j = i + 1; j < n; ++j) {
            for (std::uint64_t k = j + 1; k < n; ++k) {
                ++count;
            }
        }
    }
    return count;
}

inline std::uint64_t halvingSum(std::uint64_t n) {
    std::uint64_t count = 0;
    for (std::uint64_t i = n; i > 0; i /= 2) {
        for (std::uint64_t j = 0; j < i; ++j) {
            ++count;
        }
    }
    return count;
}

}  // namespace loops

#endif  // SDP_W01_LOOPS_H_
